using Microsoft.AspNetCore.Mvc;
using EmployeeApi.DTOs;
using EmployeeApi.Models;
using Employees.Interfaces;
using EmployeeApi.Exceptions;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication; // IMPORTED: Required for IMapper usage

namespace Employees.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class EmployeeController : ControllerBase
    {
        private readonly ILogger<EmployeeController> _logger;
        private readonly IEmployee _employeeRepo;
        private readonly IMapper _mapper; // ADDED: Private field for AutoMapper instance
        private readonly HttpClient _httpClient;

        // UPDATED: Injected IMapper into the constructor
        public EmployeeController(IEmployee employeeRepo, ILogger<EmployeeController> logger, IMapper mapper, HttpClient httpClient)
        {
            _employeeRepo = employeeRepo;
            _logger = logger;
            _mapper = mapper; // ASSIGNED: Initialized AutoMapper
            _httpClient = httpClient;
        }

        [HttpGet("GetEmployees")]
        [Authorize]
        public async Task<ActionResult<ApiResponse<IEnumerable<EmployeeDto>>>> GetEmployees()
        {
            var employees = await _employeeRepo.GetEmployees();

            if (employees == null || !employees.Any())
                throw new NotFoundException("No employees found");

            // AUTOMAPPED: Replaced manual LINQ projection select loop with automated collection mapping
            var dtoList = _mapper.Map<IEnumerable<EmployeeDto>>(employees);

            _logger.LogInformation("Retrieved {Count} employees", dtoList.Count());

            return Ok(new ApiResponse<IEnumerable<EmployeeDto>>
            {
                StatusCode = StatusCodes.Status200OK,
                Message = "Employees retrieved successfully",
                Data = dtoList
            });
        }

        [HttpGet("GetEmployeeById/{id}")]
        public async Task<ActionResult<ApiResponse<EmployeeDto>>> GetEmployeeById(int id)
        {
            if (id <= 0)
                throw new ValidationException("Invalid Employee ID");

            var result = await _employeeRepo.GetEmployeeById(id);
            if (result == null)
                throw new NotFoundException($"Employee with ID {id} not found");

            // AUTOMAPPED: Replaced manual object property copy assignment block
            var dto = _mapper.Map<EmployeeDto>(result);

            _logger.LogInformation("Employee {Id} retrieved successfully", dto.EmpId);

            return Ok(new ApiResponse<EmployeeDto>
            {
                StatusCode = StatusCodes.Status200OK,
                Message = "Employee retrieved successfully",
                Data = dto
            });
        }

        [HttpPost("AddEmployee")]
        [Authorize]
        // REFACTORED: Changed input parameter type to CreateEmployeeDto because EmpId is generated by DB identity configuration
        public async Task<ActionResult<ApiResponse<EmployeeDto>>> AddEmployee([FromBody] CreateEmployeeDto createEmployeeDto)
        {
            if (createEmployeeDto == null)
                throw new ValidationException("Invalid Employee Input For Addition");

            // AUTOMAPPED: Transformed incoming registration dto schema structure directly into our main domain Entity
            var employee = _mapper.Map<Employee>(createEmployeeDto);

            var result = await _employeeRepo.AddEmployee(employee);
            if (result == null)
                throw new Exception("Error In Addition of Employee");

            // AUTOMAPPED: Converted generated database record result back out to read-only wrapper dto for user response tracking
            var dto = _mapper.Map<EmployeeDto>(result);

            _logger.LogInformation("Employee {Id} added successfully", dto.EmpId);

            //Call funtion and pass JWT token with the request
            var jwtToken = await HttpContext.GetTokenAsync("access_token");

            var functionurl = "https://functionappwithmicroname-cta4cmebfja5a0d7.centralindia-01.azurewebsites.net/api/Employee/{id}";

            var request = new HttpRequestMessage(HttpMethod.Post, functionurl);

            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwtToken);

            var response = await _httpClient.SendAsync(request);
            var content = await response.Content.ReadAsStringAsync();


            return CreatedAtAction(nameof(GetEmployeeById), new { id = dto.EmpId }, new ApiResponse<EmployeeDto>
            {
                StatusCode = StatusCodes.Status201Created,
                Message = "Employee has been Added Successfully!",
                Data = dto
            });
        }

        [HttpPut("UpdateEmployee")]
        public async Task<ActionResult<ApiResponse<EmployeeDto>>> UpdateEmployee([FromBody] EmployeeDto employeedto)
        {
            if (employeedto == null)
                throw new ValidationException("Invalid Employee Input For Update");

            // AUTOMAPPED: Utilized ReverseMap configurations tracking rules to construct database model data tracking records
            var emp = _mapper.Map<Employee>(employeedto);

            var result = await _employeeRepo.UpdateEmployee(emp);
            if (result == null)
                throw new NotFoundException($"Employee with ID {employeedto.EmpId} not found or could not be updated");

            // AUTOMAPPED: Standardizing response structure extraction rules effortlessly
            var dto = _mapper.Map<EmployeeDto>(result);

            _logger.LogInformation("Employee {Id} updated successfully", dto.EmpId);

            return Ok(new ApiResponse<EmployeeDto>
            {
                StatusCode = StatusCodes.Status200OK,
                Message = "Employee has been Updated Successfully!",
                Data = dto
            });
        }

        [HttpDelete("DeleteEmployee/{id}")]
        public async Task<ActionResult<ApiResponse<bool>>> DeleteEmployee(int id)
        {
            if (id <= 0)
                throw new ValidationException("Invalid Employee Input For Deletion");

            var result = await _employeeRepo.DeleteEmployee(id);
            if (!result)
                throw new NotFoundException($"Employee with ID {id} not found or could not be deleted");

            _logger.LogInformation("Employee {Id} deleted successfully", id);

            return Ok(new ApiResponse<bool>
            {
                StatusCode = StatusCodes.Status200OK,
                Message = "Employee has been Deleted Successfully",
                Data = true
            });
        }

        [HttpGet("GetEmployeeDeptLocDetails")]
        public async Task<ActionResult<ApiResponse<IEnumerable<EmployeeDeptLocDto>>>> GetEmployeeDeptLocDetails()
        {
            var result = await _employeeRepo.GetEmployeeDeptLocDetails();
            if (result == null || !result.Any())
                throw new NotFoundException("No Employee Location Details Found");

            var dtolist = _mapper.Map<IEnumerable<EmployeeDeptLocDto>>(result);
            return Ok(new ApiResponse<IEnumerable<EmployeeDeptLocDto>>
            {
                StatusCode = StatusCodes.Status200OK,
                Message = "Employee Location Details Retrieved Successfully",
                Data = dtolist
            });

        }





        [HttpGet("FetchEmployeesWithKeySetPagination/{lastEmpId?}")]
        public async Task<ActionResult<ApiResponse<EmployeeDto>>> FetchEmployeesWithKeySetPagination(int? lastEmpId = null)
        {
            if (lastEmpId <= 0)
                throw new ValidationException("Invalid Employee ID");

            var result = await _employeeRepo.FetchEmployeesWithKeySetPagination(lastEmpId);
            if (result == null)
                throw new NotFoundException($"Employee with ID {lastEmpId} not found");

            // AUTOMAPPED: Replaced manual object property copy assignment block
            var dto = _mapper.Map<IEnumerable<EmployeeDto>>(result);

            _logger.LogInformation("Employee {Id} retrieved successfully", dto.FirstOrDefault()?.EmpId);

            return Ok(new ApiResponse<IEnumerable<EmployeeDto>>
            {
                StatusCode = StatusCodes.Status200OK,
                Message = "Employee retrieved successfully",
                Data = dto
            });
        }
    }





}